services:
  mon-backend:
    build:
      context: ./backend
    container_name: mon-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@mon-db:5432/portfolio
    depends_on:
      - mon-db

  mon-frontend:
    build:
      context: ./frontend
    container_name: mon-frontend
    ports:
      - "3000:80"
    depends_on:
      - mon-backend

  mon-db:
    image: postgres:13
    container_name: mon-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
